source "https://rubygems.org"

gem "jekyll", "~> 3.9.3"
gem "github-pages"
gem "jekyll-email-protect"
gem "jekyll-feed"
gem "jekyll-imagemagick"
gem "jekyll-minifier"
gem "jekyll-paginate-v2"
gem "jekyll-scholar"
gem "jekyll-sitemap"
gem "jekyll-link-attributes"
gem "jekyll-twitter-plugin"
gem "jemoji"
gem "webrick"